name: Push Docker Image
description: Tag and push Docker image to Docker Hub
inputs:
  docker_username:
    description: "Docker Hub Username"
    required: true
    default: "luizlima558"
  image_name:
    description: "Name of the Docker image"
    required: false
    default: $DOCKER_IMAGE_NAME
  tag_name:
    description: "Name of the Docker image"
    required: false
runs:
  using: composite
  steps:
    - name: Tag Docker Image
      run: docker tag ${{ inputs.image_name }} ${{ inputs.docker_username }}/academy-actions:${{ inputs.tag_name }}
      shell: bash
    - name: Push Docker Image
      run: docker push ${{ inputs.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag_name }}
      shell: bash