name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build Docker Image
        run: docker build . --file src/main/docker/Dockerfile.jvm --tag academy:$(date +%s)

      - name: List Docker Images
        run: docker images | grep academy

      - uses: LippoKo/academy-v2/.github/actions/maven_build@main
      - uses: LippoKo/academy-v2/.github/actions/docker_build@main
        with:
          dockerfile_path: src/main/docker/Dockerfile.jvm
          image_name: academy
          tag_name: $(date +%s)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: LippoKo/academy-v2/.github/actions/docker_push@main
        with:
          docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
          image_name: academy